### ISSUE TITLE
Mixin error with Capes, please help? 

### ISSUE THREAD

**Issue by Dumpling00** [Ryhon0/CraftableCapes#2]
Hello! Saw your mod on modrinth and instantly fell in love, had to had it in my modpack.

But I'm getting a mixin error however and I was wondering if you could kindly help making sense of this and possibly find a fix.

https://mclo.gs/REnMRvk

This is on Fabric 1.20.1

Thank you in advance for your time.

**Comment by Ryhon0** [comment]
Use Java 21 instead of 17, I forgot to change it when backporting

**Comment by Ryhon0** [comment]
1.0.2 is compatible with Java 17
https://modrinth.com/mod/craftablecapes/version/1.0.2
