### ISSUE TITLE
Typos in the names of some capes

### ISSUE THREAD

**Issue by myriadh** [Ryhon0/CraftableCapes#3]
![image](https://github.com/Ryhon0/CraftableCapes/assets/171615242/7f8e6c07-4ad2-459d-be1b-88461fb9b5e4)
![image](https://github.com/Ryhon0/CraftableCapes/assets/171615242/20d5b6ee-3d33-4141-a89a-f9dc93898685)
![image](https://github.com/Ryhon0/CraftableCapes/assets/171615242/b82c96fb-bee2-4fb8-aa96-09b1b52457fc)
![image](https://github.com/Ryhon0/CraftableCapes/assets/171615242/449b8766-9339-44bf-bc13-5e4883f87a47)
![image](https://github.com/Ryhon0/CraftableCapes/assets/171615242/62573e64-8f92-4b18-bb4a-37d471bdf644)
![image](https://github.com/Ryhon0/CraftableCapes/assets/171615242/a6923eb6-e9a8-4ed7-9ebf-9b037863d3be)
![image](https://github.com/Ryhon0/CraftableCapes/assets/171615242/0357442a-96d3-4271-b8b2-d3d08a9b0863)
There are so many of these typos that I can't tell if they are meant to be on purpose or not, but just thought I should report it anyways

**Comment by Ryhon0** [comment]
The cherry blossom cape is incorrect, the others are form the 2023 April fool's update and are intentionally misspelled
