### ISSUE TITLE
mcc 15th cape and villager experience cape is missing

### ISSUE THREAD

**Issue by GodlyFirecracker** [Ryhon0/CraftableCapes#4]
this mod havent been updated,there is mcc 15th cape,recipe is golden crown surrounded by 2 red wools to the left and right,and 1st row and 3rd row is yellow wool
as for villager experience cape,its an emerald surrounded by 8 purple wools

**Comment by GodlyFirecracker** [comment]
![bandicam 2024-10-01 17-26-25-526](https://github.com/user-attachments/assets/3d0a759c-0e3e-4082-a755-d681db6c54ea)

**Comment by Ryhon0** [comment]
The MCC cape was added in 1.0.3

**Comment by GodlyFirecracker** [comment]
then this was still an issue since the vilager exp cape

**Comment by Ryhon0** [comment]
Now available in 1.1.0
