### ISSUE TITLE
Capes display abnormal

### ISSUE THREAD

**Issue by RbtLee** [Ryhon0/CraftableCapes#5]
In Minecraft's 1.21 Fabric game, Prism and Downpour capes display abnormally.
![2024-10-04_00 26 26](https://github.com/user-attachments/assets/e3b57c69-3a0b-4218-b3fc-85fabeadf0f9)

**Comment by Ryhon0** [comment]
My bad. Thanks for reporting

**Comment by Ryhon0** [comment]
Fixed in 1.1.1
